//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habib_Chemical_Software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash_Drawer
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int total_amount { get; set; }
        public Nullable<int> withdraw_by { get; set; }
        public string withdraw_reason { get; set; }
        public Nullable<int> withdraw_amount { get; set; }
        public Nullable<int> store_by { get; set; }
        public string store_reason { get; set; }
        public Nullable<int> store_amount { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
