//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habib_Chemical_Software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Due
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public System.DateTime date { get; set; }
        public int payment_amount { get; set; }
        public string payment_type { get; set; }
        public string bank_name { get; set; }
        public int check_number { get; set; }
        public Nullable<System.DateTime> check_expire_date { get; set; }
        public bool check_cleared { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
