//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habib_Chemical_Software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Product
    {
        public int id { get; set; }
        public int transaction_id { get; set; }
        public int product_id { get; set; }
        public int product_amount { get; set; }
        public int product_price_id { get; set; }
        public int total_price { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product_Price Product_Price { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
